title: ğŸ–
author: Helena Rasche
email: hxr@hx42.org
description: ""
baseurl: ""
url: "https://hexylena.github.io/"
github_username: hexylena

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
